sudo: false
language: node_js
cache: yarn
node_js: '8'
before_script:
  - yarn build
script:
  - yarn test
notifications:
  email: false
branches:
  except:
    - experimental
    - 1.43
    - commands
