sudo: false
language: node_js
cache: yarn
node_js: '8'
before_script:
  - npm install -g phantomjs@1.9.20
  - yarn build
notifications:
  email: false
branches:
  except:
    - experimental
    - 1.43
    - commands
